schema_version: 20180708
name: peak-frequency-plotter
version: 0.0.1
runtime: python3.7
entrypoint: python3 func.py
memory: 2000
timeout: 300
triggers:
- name: peak-frequency-plotter
  type: http
  source: /peak-frequency-plotter
