schema_version: 20180708
name: csv-converter
version: 0.0.7
runtime: go
build_image: denismakogon/ffmpeg-debian:golang
run_image: denismakogon/ffmpeg-debian:runtime
entrypoint: ./func
memory: 1500
timeout: 300
triggers:
- name: csv-converter
  type: http
  source: /csv-converter
