schema_version: 20180708
name: timecode-statistics
version: 0.0.5
runtime: python3.7
entrypoint: python3 func.py
format: http-stream
memory: 2000
timeout: 300
triggers:
- name: timecode-statistics
  type: http
  source: /timecode-statistics
