schema_version: 20180708
name: audio-processor
version: 0.0.8
runtime: go
build_image: denismakogon/ffmpeg-debian:golang as build-stage
run_image: denismakogon/ffmpeg-debian:runtime
entrypoint: ./func
memory: 1024
timeout: 300
triggers:
- name: audio-processor
  type: http
  source: /audio-processor
