schema_version: 20180708
name: wav-plotter
version: 0.0.10
runtime: python3.7
entrypoint: python3 func.py
format: http-stream
memory: 2000
timeout: 300
triggers:
- name: wav-plotter
  type: http
  source: /wav-plotter
